#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("TicTacToe.Resource", IsApplication=true)]

namespace TicTacToe
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_left = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_in_right = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int slide_out_left = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int slide_out_right = 2130968579;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int draw = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int o = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int tictactoe = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int x = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060008
			public const int btnCancel = 2131099656;
			
			// aapt resource value: 0x7f060016
			public const int btnCancel1 = 2131099670;
			
			// aapt resource value: 0x7f060029
			public const int btnCancel2 = 2131099689;
			
			// aapt resource value: 0x7f060024
			public const int btnCancel3 = 2131099684;
			
			// aapt resource value: 0x7f060003
			public const int btnEnglish = 2131099651;
			
			// aapt resource value: 0x7f06002e
			public const int btnExit = 2131099694;
			
			// aapt resource value: 0x7f06002d
			public const int btnExitToMenu = 2131099693;
			
			// aapt resource value: 0x7f060002
			public const int btnRussian = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int btnSubmenu1 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int btnSubmenu2 = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int button1 = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int button2 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int button3 = 2131099661;
			
			// aapt resource value: 0x7f06000f
			public const int button4 = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int button5 = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int button6 = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int button7 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int button8 = 2131099668;
			
			// aapt resource value: 0x7f060015
			public const int button9 = 2131099669;
			
			// aapt resource value: 0x7f060019
			public const int computerButton1 = 2131099673;
			
			// aapt resource value: 0x7f06001a
			public const int computerButton2 = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int computerButton3 = 2131099675;
			
			// aapt resource value: 0x7f06001d
			public const int computerButton4 = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int computerButton5 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int computerButton6 = 2131099679;
			
			// aapt resource value: 0x7f060021
			public const int computerButton7 = 2131099681;
			
			// aapt resource value: 0x7f060022
			public const int computerButton8 = 2131099682;
			
			// aapt resource value: 0x7f060023
			public const int computerButton9 = 2131099683;
			
			// aapt resource value: 0x7f06002b
			public const int developer = 2131099691;
			
			// aapt resource value: 0x7f060005
			public const int gameName = 2131099653;
			
			// aapt resource value: 0x7f060026
			public const int imageWinner = 2131099686;
			
			// aapt resource value: 0x7f060028
			public const int restartGame1 = 2131099688;
			
			// aapt resource value: 0x7f06002c
			public const int restartGame2 = 2131099692;
			
			// aapt resource value: 0x7f06000a
			public const int tableRow1 = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int tableRow2 = 2131099662;
			
			// aapt resource value: 0x7f060012
			public const int tableRow3 = 2131099666;
			
			// aapt resource value: 0x7f060018
			public const int tableRow4 = 2131099672;
			
			// aapt resource value: 0x7f06001c
			public const int tableRow5 = 2131099676;
			
			// aapt resource value: 0x7f060020
			public const int tableRow6 = 2131099680;
			
			// aapt resource value: 0x7f060027
			public const int textWinner = 2131099687;
			
			// aapt resource value: 0x7f060017
			public const int tlComputerMenu = 2131099671;
			
			// aapt resource value: 0x7f060001
			public const int tlLanguages = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int tlMainMenu = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int tlSubmenu1 = 2131099657;
			
			// aapt resource value: 0x7f060025
			public const int tlSubmenu2 = 2131099685;
			
			// aapt resource value: 0x7f06002a
			public const int tlSubmenu3 = 2131099690;
			
			// aapt resource value: 0x7f060000
			public const int viewFlipper = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
